all:
	cd create_pod; make
	cd list_pod; make
	cd list_pod_incluster; make
	cd exec_provider; make
	cd generic; make
	cd auth_provider; make

clean:
	cd create_pod; make clean
	cd list_pod; make clean
	cd list_pod_incluster; make clean
	cd exec_provider; make clean
	cd generic; make clean
	cd auth_provider; make clean
